services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8082:3000"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:4000"
    env_file: 
      - .env.production  # Specify which env file to use
    volumes:
      - uploads:/app/public/uploads
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  uploads:
