import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme toggle/theme-provider";
import { Header } from "@/components/header";
import { Toaster } from "@/components/ui/sonner";
import "./animations.css";
import { Footer } from "@/components/footer";
import { StoreProvider } from "@/providers/storeProvider";
import { ArrowUpToLine } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Coin-Beats",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg", // Define PNG favicon here
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${inter.className}  antialiased relative min-h-[100vh]`}
        >
          {/* <div className="gradient-bg-container z-0">
            <div className="primary-gradient blob-morph " />
            <div className="secondary-gradient-1 animate-float blob-morph " />
            <div className="secondary-gradient-2 animate-float-reverse blob-morph " />
          </div> */}
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster />
            <Header />

            <main className="flex-1 ">{children}</main>

            <footer className="pt-0 pb-20">
              <div className="px-2 text-center text-sm text-muted-foreground">
                © 2025 coinbeats All rights reserved.
              </div>
            </footer>
            <Footer />
          </ThemeProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
